MaceShockwave = true
MaceShockwaveSize = 1.0
MaceShockwaveOpacity = 0.5
MaceSpark = true
MaceFlash = true
LegacyMaceShockwave = false
ShieldEffect = true
ArmorParticles = true
WindParticles = true
CustomTotemEffect = true
TotemEffectOpacity = 1.0
PlayerDeathEffect = true
GlideIcon = false
PearlTrailParticles = true
PearlTrailOpacity = 0.5
PearlWhiteList = []
SelfPearlColor = -256
AllyPearlColor = -16776961
OtherPearlColor = -65536
CustomHitbox = false
PearlHitboxColors = false
MobHitboxOpacity = 0.3
PlayerHitboxOpacity = 1.0
HitboxFadeDistance = 15.0
HitboxProjectileFadeDistance = 5.0
